FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential wget ca-certificates tar && \
    wget --no-check-certificate 'https://www.slac.stanford.edu/~abh/bbcp/bbcp.tgz' -O bbcp.tgz && \
    tar xzf bbcp.tgz && \
    cd bbcp/src && \
    make Linux && \
    cp ../bin/*/bbcp /usr/local/bin/ && \
    chmod +x /usr/local/bin/bbcp && \
    cd / && \
    rm -rf bbcp bbcp.tgz && \
    apt-get purge -y build-essential wget tar && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["bbcp"]