name: Build and Deploy BBCP Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
    paths:
      - 'bbcp/**'
      - '.github/workflows/bbcp-docker-build-deploy.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'bbcp/**'
      - '.github/workflows/bbcp-docker-build-deploy.yml'

env:
  REGISTRY: docker.io
  # TODO: Replace 'your-dockerhub-username' with your actual Docker Hub username
  IMAGE_NAME: marioja/bbcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{branch}}-{{sha}},enable={{is_default_branch}}    - name: Get BBCP version from source
      id: bbcp-version
      run: |
        # Clone the bbcp repository to extract version
        git clone https://github.com/marioja/bbcp.git temp-bbcp
        
        # Extract version from bbcp_Version.C
        if [ -f "temp-bbcp/src/bbcp_Version.C" ]; then
          VERSION=$(grep 'Version.*=' temp-bbcp/src/bbcp_Version.C | sed 's/.*Version: \([^"]*\)".*/\1/' | head -1)
          echo "Extracted BBCP version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "Could not find bbcp_Version.C, using default"
          echo "version=17.12.00.00.1" >> $GITHUB_OUTPUT
        fi
        
        # Clean up
        rm -rf temp-bbcp

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./bbcp
        file: ./bbcp/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max        build-args: |
          BBCP_VERSION_EXTRACTED=${{ steps.bbcp-version.outputs.version }}
          BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          VCS_REF=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          VERSION_TAG=${{ github.ref_name }}

    - name: Update Docker Hub description
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.IMAGE_NAME }}
        readme-filepath: ./bbcp/README.md

